import type { ResolvedConfig } from '../types.js';

export const DEFAULTS: ResolvedConfig = {
  ide: {
    theme: 'tokyo-night',
    font: 'JetBrains Mono',
    font_size: 15,
    show_line_numbers: true,
    show_minimap: false,
    show_file_tree: true,
    indent_guides: true,
    bracket_pair_colorization: true,
  },
  platform: {
    platform: 'tiktok',
    resolution: '1080x1920',
    fps: 60,
    output_path: './output/video.mp4',
  },
  typing: {
    wpm_base: 65,
    wpm_ramp_factor: 3.5,
    ramp_start: 0.35,
    ramp_end: 0.75,
    typo_rate: 0.04,
    typo_correction_delay: [0.4, 1.2],
    pause_on_new_function: [0.8, 2.0],
    pause_on_new_line: [0.05, 0.3],
    cursor_hover: true,
    show_autocomplete: true,
    autocomplete_accept_delay: [0.6, 1.4],
  },
  virality: {
    hook_enabled: true,
    hook_text: '',
    hook_duration: 2.5,
    hook_style: 'bold_center',
    caption_mode: 'none',
    payoff_slowdown: 0.3,
    payoff_moment: 'auto',
    progress_bar: true,
    branding: { watermark: '', position: 'bottom_right' },
  },
  audio: {
    music_track: '',
    music_volume: 0.28,
    keystroke_pack: 'cherry_mx_blue',
    keystroke_volume: 0.75,
    terminal_sound: true,
  },
  terminal: {
    terminal_enabled: false,
    terminal_command: '',
    terminal_output_file: '',
    terminal_position: 'split_bottom',
    terminal_appear_at: 'end',
  },
  zoom_on_key_lines: false,
  zoom_factor: 1.08,
  multi_file: false,
  batch: 1,
};
