#!/usr/bin/env bash
# Run after all videos are generated
# Extracts preview GIFs, uploads to GitHub release, updates README

set -e
cd /PROJECTS/LLM/viral-coder

VIDEOS_DIR="examples/videos"
GIFS_DIR="examples/gifs"
RELEASE_TAG="v1.0.6-examples"
REPO="SergiuPogor/viral-coder"
BASE_URL="https://github.com/${REPO}/releases/download/${RELEASE_TAG}"

mkdir -p "$GIFS_DIR"

echo "→ Extracting preview GIFs..."
for mp4 in "$VIDEOS_DIR"/*.mp4; do
  name=$(basename "$mp4" .mp4)
  gif="$GIFS_DIR/${name}.gif"
  echo "  $name..."
  # 4s clip from 8s mark, 540w, 12fps
  ffmpeg -y -ss 8 -t 4 -i "$mp4" \
    -vf "fps=12,scale=540:-1:flags=lanczos,split[s0][s1];[s0]palettegen=max_colors=64[p];[s1][p]paletteuse=dither=bayer" \
    "$gif" 2>/dev/null
done
echo "✓ GIFs done"

# Delete old release if exists
echo "→ Deleting old release..."
gh release delete "$RELEASE_TAG" --repo "$REPO" --yes 2>/dev/null || true

# Create new release with all MP4s + GIFs
echo "→ Creating GitHub release ${RELEASE_TAG}..."
gh release create "$RELEASE_TAG" \
  --repo "$REPO" \
  --title "Example Videos v1.0.6 — All Themes & Languages" \
  --notes "Example videos generated by viral-coder v1.0.6 with fixed font sizes (32-48px) and proper phone layout." \
  "$VIDEOS_DIR"/*.mp4 \
  "$GIFS_DIR"/*.gif

echo "✓ Release created"

# Build README examples section
echo "→ Updating README..."
cat > /tmp/readme_examples.md << EXAMPLES

## 🎬 Examples

All videos auto-generated by viral-coder. No editing, no screen recording.

### 8 IDE Themes

| Theme | Preview | Full Video |
|-------|---------|------------|
| tokyo-night | ![tokyo-night](${BASE_URL}/theme-tokyo-night.gif) | [▶ Watch](${BASE_URL}/theme-tokyo-night.mp4) |
| dracula | ![dracula](${BASE_URL}/theme-dracula.gif) | [▶ Watch](${BASE_URL}/theme-dracula.mp4) |
| catppuccin | ![catppuccin](${BASE_URL}/theme-catppuccin.gif) | [▶ Watch](${BASE_URL}/theme-catppuccin.mp4) |
| github-dark | ![github-dark](${BASE_URL}/theme-github-dark.gif) | [▶ Watch](${BASE_URL}/theme-github-dark.mp4) |
| monokai-pro | ![monokai-pro](${BASE_URL}/theme-monokai-pro.gif) | [▶ Watch](${BASE_URL}/theme-monokai-pro.mp4) |
| one-dark | ![one-dark](${BASE_URL}/theme-one-dark.gif) | [▶ Watch](${BASE_URL}/theme-one-dark.mp4) |
| nord | ![nord](${BASE_URL}/theme-nord.gif) | [▶ Watch](${BASE_URL}/theme-nord.mp4) |
| gruvbox | ![gruvbox](${BASE_URL}/theme-gruvbox.gif) | [▶ Watch](${BASE_URL}/theme-gruvbox.mp4) |

### 7 Languages

| Language | Hook | Preview | Full Video |
|----------|------|---------|------------|
| TypeScript | Async retry that saves prod at 3am | ![ts](${BASE_URL}/lang-typescript.gif) | [▶ Watch](${BASE_URL}/lang-typescript.mp4) |
| Python | One-liners that replace 50 lines | ![py](${BASE_URL}/lang-python.gif) | [▶ Watch](${BASE_URL}/lang-python.mp4) |
| Rust | Zero-copy parser, zero allocations | ![rs](${BASE_URL}/lang-rust.gif) | [▶ Watch](${BASE_URL}/lang-rust.mp4) |
| Go | Fan-out goroutines, 10x faster | ![go](${BASE_URL}/lang-go.gif) | [▶ Watch](${BASE_URL}/lang-go.mp4) |
| JavaScript | Most over-engineered FizzBuzz ever | ![js](${BASE_URL}/lang-javascript.gif) | [▶ Watch](${BASE_URL}/lang-javascript.mp4) |
| Python decorators | retry/memoize/rate_limit chained | ![py2](${BASE_URL}/lang-python2.gif) | [▶ Watch](${BASE_URL}/lang-python2.mp4) |
| SQL | Recursive CTE graph traversal | ![sql](${BASE_URL}/lang-sql.gif) | [▶ Watch](${BASE_URL}/lang-sql.mp4) |

> Source files: [examples/code/](./examples/code/)

EXAMPLES

# Replace existing Examples section in README
python3 - << 'PYEOF'
import re
with open('README.md', 'r') as f:
    content = f.read()
with open('/tmp/readme_examples.md', 'r') as f:
    new_section = f.read()
# Remove old examples section if exists
content = re.sub(r'\n## 🎬 Examples.*?(?=\n## |\Z)', '', content, flags=re.DOTALL)
# Insert after badges block
insert_after = '</p>\n'
idx = content.find(insert_after)
if idx != -1:
    content = content[:idx + len(insert_after)] + new_section + content[idx + len(insert_after):]
else:
    content = content + new_section
with open('README.md', 'w') as f:
    f.write(content)
print('README updated')
PYEOF

# Commit + push
git add -A
git add examples/gifs/ 2>/dev/null || true
git commit -m "feat: add GIF previews in README for all themes and languages (v1.0.6-examples)"
git push

echo ""
echo "✅ ALL DONE!"
echo "   Release: https://github.com/${REPO}/releases/tag/${RELEASE_TAG}"
echo "   README:  https://github.com/${REPO}#-examples"
openclaw system event --text "Done: all viral-coder example videos + GIFs uploaded, README updated with inline previews" --mode now
